FROM node:14-alpine AS build
WORKDIR /usr/src/app
COPY frontend/package*.json ./
RUN npm install
COPY frontend/. .
RUN npm run build

FROM node:14-alpine AS serve
RUN npm install -g serve
WORKDIR /usr/src/app
COPY --from=build /usr/src/app/build ./
EXPOSE 3000
CMD ["serve", "-s", ".", "-l", "3000"]
