version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_BASE_URL: "http://mock-service:8000"
    depends_on:
      - mock-service
    networks:
      - app-network

  mock-service:
    build: ./services/mock-service
    container_name: mock-service
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
