version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_BASE_URL: "http://backend:5000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"

  service1:
    build: ./services/service1
    ports:
      - "8081:8080"

  service2:
    build: ./services/service2
    ports:
      - "8082:8080"
